name: run main.py

on:
  schedule:
    - cron: '* * * * *' # every day at 13:50 check crontab.guru

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run main.py
        # env:
        #   SLCM_USERNAME: ${{ secrets.SLCM_USERNAME }}
        #   SLCM_PASSWORD: ${{ secrets.SLCM_PASSWORD }}
        #   INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        #   INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        run: python -u src/main.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # branch: main 
          # branch: master
          branch: ${{ github.ref }}